[package]
name = "day11"
version = "0.1.0"
authors = ["sinewyk <sinewyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grid = "0.2.3"
itertools = "0.10.0"

[dev-dependencies]
indoc = "1.0.3"
